name: Snyk Security
 
on:
  push:
    branches:
      - master
 
jobs:
  snyk:
    runs-on: ubuntu-22.04
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Node.js (if using Node.js)
      uses: actions/setup-node@v3
      with:
        node-version: '16'
 
    - name: Install dependencies
      run: npm install
 
    - name: Authenticate Snyk
      run: snyk auth "${{ secrets.SNYK_TOKEN }}"
 
    - name: Run Snyk test
      run: snyk test
